# -*- coding: utf-8 -*-
"""clean_and_eda

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UpSEcg2UuSUodnJimvqRiznNMTkkb_ro
"""

import pandas as pd

"""# **Task 1 — Load and inspect**"""

orders = pd.read_csv("orders.csv")
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")

print("\nOrders Shape (before cleaning):")
print(orders.shape)

print("\nCustomers Shape:")
print(customers.shape)

print("\nProducts Shape:")
print(products.shape)

"""# **Task 2 — Standardize payment_method casing**"""

print(orders["payment_method"].unique())

orders["payment_method"] = (
    orders["payment_method"]
    .str.strip()
    .str.upper()
)

print("\nUnique values AFTER cleaning:")
print(sorted(orders["payment_method"].unique()))

print("\nCounts after standardization:")
print(orders["payment_method"].value_counts())

"""# Task 3 — Remove duplicate orders"""

duplicate_columns = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned"
]

duplicates = orders.duplicated(
    subset=duplicate_columns,
    keep="first"
)

print("\nNumber of duplicate rows:")
print(duplicates.sum())

print("\nDropped Order IDs:")
print(orders.loc[duplicates, "order_id"].tolist())

orders_clean = orders.loc[~duplicates].copy()

print("\nShape after removing duplicates:")
print(orders_clean.shape)

"""# **Task 4 — Impute missing values**"""

discount_missing = orders_clean["discount_pct"].isnull().sum()
rating_missing = orders_clean["rating"].isnull().sum()

print("\nMissing discount values:")
print(discount_missing)

print("Missing ratings:")
print(rating_missing)

median_rating = orders_clean["rating"].median()

print("\nMedian Rating:")
print(median_rating)

orders_clean["discount_pct"] = orders_clean["discount_pct"].fillna(0)

orders_clean["rating"] = orders_clean["rating"].fillna(
    median_rating
)

print("\nMissing values after imputation:")
print(
    orders_clean[
        ["discount_pct", "rating"]
    ].isnull().sum()
)

print("\nCurrent cleaned shape:")
print(orders_clean.shape)

"""# **Task 5 — Merge and reconcile against Part 1**"""

merged = (
    orders_clean
    .merge(products, on="product_id", how="inner")
    .merge(customers, on="customer_id", how="inner")
)

merged["order_value"] = (
    merged["quantity"]
    * merged["price"]
    * (1 - merged["discount_pct"] / 100)
)

merged["order_value"] = merged["order_value"].round(2)

print("\nMerged Shape:")
print(merged.shape)

clean_total = round(merged["order_value"].sum(), 2)

print("\nTotal Revenue (Clean Data):")
print(clean_total)

"""**Verify duplicate revenue**"""

duplicate_orders = orders.loc[duplicates].copy()

duplicate_orders = (
    duplicate_orders
    .merge(products, on="product_id")
)

duplicate_orders["discount_pct"] = duplicate_orders["discount_pct"].fillna(0)

duplicate_orders["order_value"] = (
    duplicate_orders["quantity"]
    * duplicate_orders["price"]
    * (1 - duplicate_orders["discount_pct"]/100)
)

duplicate_total = round(duplicate_orders["order_value"].sum(),2)

print("\nRevenue of Duplicate Orders:")
print(duplicate_total)

raw_total = 99860.20

print("\nDifference:")
print(round(raw_total-clean_total,2))

"""**Print reconciliation note**"""

print("\nReconciliation Note:")
print(
    f"""
The cleaned revenue is ₹{clean_total:.2f}, whereas the raw SQL report
was ₹99,860.20.

The difference is exactly ₹{duplicate_total:.2f}, which equals the
combined revenue of the five duplicate orders removed during
Task 3.

Discount imputation (NULL -> 0) and rating imputation
(NULL -> median) do not change revenue because order_value depends
only on quantity, price and discount percentage.
"""
)

"""# **Task 6 – IQR Outliers**"""

Q1 = merged["quantity"].quantile(0.25)
Q3 = merged["quantity"].quantile(0.75)

IQR = Q3-Q1

lower = Q1-1.5*IQR
upper = Q3+1.5*IQR

print("Q1 :",Q1)
print("Q3 :",Q3)
print("IQR :",IQR)
print("Lower :",lower)
print("Upper :",upper)

merged["is_outlier"] = (
    (merged["quantity"]<lower)
    |
    (merged["quantity"]>upper)
)

outliers = merged[merged["is_outlier"]]

print("\nOutliers")

print(
    outliers[
        ["order_id","quantity"]
    ]
)

print("\nNumber of outliers")
print(len(outliers))

"""# **Task 7 — Hypothesis: does COD have a higher return rate?**"""

print("""
Hypothesis:
Customers paying by COD have a higher return rate.
""")

payment_stats = (
    merged
    .groupby("payment_method")["returned"]
    .agg(["count","mean"])
)

payment_stats["return_rate_pct"] = (
    payment_stats["mean"]*100
).round(1)

print(payment_stats)

print("\nConclusion:")
print("Hypothesis Confirmed")

"""# **Task 8 — Multi-level segmentation**"""

segment = (
    merged
    .groupby(
        ["payment_method","city_tier"]
    )["returned"]
    .agg(["count","mean"])
)

segment["return_rate_pct"] = (
    segment["mean"]*100
).round(1)

print(segment)

highest = segment.sort_values(
    "return_rate_pct",
    ascending=False
).head(1)

print("\nHighest Risk Segment")

print(highest)

"""# **Task 9 – Correlation**"""

corr = merged[
    [
        "rating",
        "returned",
        "discount_pct",
        "quantity"
    ]
].corr()

print(corr)

print("\nStrength Interpretation")

columns = corr.columns

for i in range(len(columns)):
    for j in range(i+1,len(columns)):

        r = corr.iloc[i,j]

        value = abs(r)

        if value <0.2:
            strength="Negligible"

        elif value<0.4:
            strength="Weak"

        elif value<0.7:
            strength="Moderate"

        else:
            strength="Strong"

        print(
            f"{columns[i]} vs {columns[j]} : {r:.2f} -> {strength}"
        )

print("\nHypothesis:")
print("Higher discounts reduce returns -> BUSTED")

"""# **Task 10 – Monthly Trend**"""

merged["order_date"]=pd.to_datetime(
    merged["order_date"]
)

merged["year_month"]=(
    merged["order_date"]
    .dt.to_period("M")
    .astype(str)
)

monthly_all=(
    merged
    .groupby("year_month")["order_value"]
    .sum()
    .round(2)
)

print("\nIncluding Outliers")

print(monthly_all)

monthly_clean=(
    merged[
        ~merged["is_outlier"]
    ]
    .groupby("year_month")["order_value"]
    .sum()
    .round(2)
)

print("\nExcluding Outliers")

print(monthly_clean)

print("""
January appears to be the highest revenue month only because two
bulk orders (O0011 and O0098) occurred in January.

After excluding these outliers, March becomes the genuine peak
revenue month.
""")

"""# **Part-3 Task 1 — narrator/findings.json**"""

# PART 3 - TASK 1
# Export findings.json

import json
import os


print("EXPORTING FINDINGS FOR GENAI NARRATOR")

# Create narrator folder if it doesn't already exist
os.makedirs("narrator", exist_ok=True)

# Create dictionary containing verified findings
findings = {
    "cleaned_total_revenue_inr": round(clean_total, 2),
    "raw_total_revenue_inr": 99860.20,
    "duplicate_reconciliation_delta_inr": round(duplicate_total, 2),

    "return_rate_by_payment": {
        "CARD": 14.7,
        "COD": 44.4,
        "UPI": 18.9
    },

    "highest_risk_segment": {
        "payment_method": "COD",
        "city_tier": 2,
        "return_rate_pct": 54.5
    },

    "true_peak_month": {
        "month": "2026-03",
        "revenue_inr": 20318.90
    },

    "outlier_inflated_month": {
        "month": "2026-01",
        "apparent_revenue_inr": 29582.10,
        "corrected_revenue_inr": 11637.10
    }
}

# Write findings to narrator/findings.json
with open("narrator/findings.json", "w") as file:
    json.dump(findings, file, indent=4)

print("\nfindings.json has been created successfully in narrator/ directory.")

#print("\nGenerated Findings:")
#print(json.dumps(findings, indent=4))

