# -*- coding: utf-8 -*-
"""visualize

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFBN41gcKyF1G1BKGq46ebUnrGDVvKED

# **Task 11 — Two visualizations**
"""

import pandas as pd
import matplotlib.pyplot as plt
import os

# ==========================================================
# Create output folder
# ==========================================================

os.makedirs("visualizations", exist_ok=True)

# ==========================================================
# Load Data
# ==========================================================

orders = pd.read_csv("orders.csv")
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")

# ==========================================================
# Standardize payment method
# ==========================================================

orders["payment_method"] = (
    orders["payment_method"]
    .str.strip()
    .str.upper()
)

# ==========================================================
# Remove duplicate orders
# ==========================================================

duplicate_columns = [
    "customer_id",
    "product_id",
    "order_date",
    "quantity",
    "discount_pct",
    "payment_method",
    "rating",
    "returned"
]

orders = orders.loc[
    ~orders.duplicated(
        subset=duplicate_columns,
        keep="first"
    )
].copy()

# ==========================================================
# Missing value treatment
# ==========================================================

orders["discount_pct"] = orders["discount_pct"].fillna(0)

orders["rating"] = orders["rating"].fillna(
    orders["rating"].median()
)

# ==========================================================
# Merge
# ==========================================================

merged = (
    orders
    .merge(products, on="product_id")
    .merge(customers, on="customer_id")
)

merged["order_value"] = (
    merged["quantity"]
    * merged["price"]
    * (1 - merged["discount_pct"] / 100)
)

# ==========================================================
# Detect Outliers
# ==========================================================

Q1 = merged["quantity"].quantile(0.25)
Q3 = merged["quantity"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

merged["is_outlier"] = (
    (merged["quantity"] < lower)
    |
    (merged["quantity"] > upper)
)

# ==========================================================
# Chart 1
# Return Rate by Payment Method
# ==========================================================

payment = (
    merged
    .groupby("payment_method")["returned"]
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

plt.figure(figsize=(7,5))

bars = plt.bar(
    payment.index,
    payment.values
)

plt.title("COD Returns at 44.4% — 3x Card")
plt.xlabel("Payment Method")
plt.ylabel("Return Rate (%)")

for bar in bars:

    height = bar.get_height()

    plt.text(
        bar.get_x() + bar.get_width()/2,
        height + 0.5,
        f"{height:.1f}%",
        ha="center"
    )

plt.tight_layout()

plt.savefig(
    "visualizations/return_rate_by_payment.png",
    dpi=300
)

plt.close()

# ==========================================================
# Chart 2
# Monthly Revenue (Outlier Corrected)
# ==========================================================

merged["order_date"] = pd.to_datetime(
    merged["order_date"]
)

merged["year_month"] = (
    merged["order_date"]
    .dt.to_period("M")
    .astype(str)
)

monthly = (
    merged[
        ~merged["is_outlier"]
    ]
    .groupby("year_month")["order_value"]
    .sum()
)

plt.figure(figsize=(8,5))

plt.plot(
    monthly.index,
    monthly.values,
    marker="o"
)

plt.title("Monthly Revenue Trend (Peak Month: March 2026)")
plt.xlabel("Month")
plt.ylabel("Revenue (₹)")

plt.tight_layout()

plt.savefig(
    "visualizations/monthly_revenue_trend.png",
    dpi=300
)

plt.close()

print("Visualizations saved successfully.")
print("1. visualizations/return_rate_by_payment.png")
print("2. visualizations/monthly_revenue_trend.png")

